### ISSUE TITLE
Factory 'createWith' doesnt work

### ISSUE THREAD

**Issue by carlosvillu** [abe33/spectacular#11]
When I try the example code

``` coffee
class User
  constructor: (@id) ->

factory 'user', class: User, ->
  createWith -> Math.floor Math.random() * 100000

  set 'name', -> 'John Doe'

  trait 'with_bike', ->
    set 'bike', -> {model: 'z750', brand: 'Kawasaki'}
```

What i get is:

```
{id: undefined, name: 'John Doe' }
```

And this happen with all my classes, the constructor never is called with the corrects values.

**Comment by abe33** [comment]
Hi @carlosvillu, 

Thanks for reporting, it's an issue with the documentation ^^'. The `createWith` helper, when called with a function block should return an array (returning a single value doesn't make sense).

The corrected version looks

``` coffeescript
class User
  constructor: (@id) ->

factory 'user', class: User, ->
  createWith -> [ Math.floor Math.random() * 100000 ]

  set 'name', -> 'John Doe'

  trait 'with_bike', ->
    set 'bike', -> {model: 'z750', brand: 'Kawasaki'}
```

I'll fix that when coming home tonight. Maybe the helper should be smart enough to wrap the returned value in an array when this case occurs, I'll think about that.

**Comment by carlosvillu** [comment]
Thx for your response. :+1: 

I will try this afternoon when i will came back at home.
